### ISSUE TITLE
How did you find number of tailed triangles?

### ISSUE THREAD

**Issue by balcilar** [leichen2018/GNN-Substructure-Counting#3]
Seems the number of tailed triangles is not consistent.
As far as I know, we can calculate the number of tailed triangle assuming A is adjacency of the simple undirected (and not self connections) graph by this python code:

((np.diag(A.dot(A.dot(A)))/2)*(A.sum(0)-2)).sum()

For instance in dataset2.bin file. Second graph's tailed triangle number was given 31, but I found it 47.
Am I wrong on this calculation or basically how did you obtain these tailed triangle numbers?

best,

**Comment by leichen2018** [comment]
Hello,

We used `https://github.com/liuxt/graphlet_counting/blob/master/Graphlet.py` to count these **induced** substructures. 

It seems your calculation is correct for counting (normally defined) tailed triangles but not for _induced-counting_. (Please check our definition for induced subgraphs in the paper.) The difference is that an induced tailed triangle requires no edge between the tail node and the other two nodes in the triangle, while a (normally defined) tailed triangle does not have such a restriction, as around line 430 of the above code. Hence, for example, a 4-clique has no induced tailed triangle but has 12 (normally defined) tailed triangles.

Hope this can help you! Please do let me know if the results are correct then.

Best,
Lei

**Comment by balcilar** [comment]
Thanks for pointing out the differences between induced and normal ones. It is clear now.
Many thanks.
